### PR TITLE
Update add.php

### PR DESCRIPTION
**Pull request by imdewan**
Removed some bugs and create a html page at pages folder

### CODE REVIEW

**Review by pepiuox — COMMENTED** [review]
Good idea, if you want to create physical pages, the change is good, but in this case they are stored in the **page** table, then when editing or building with **builder.php** all the content will be stored in the database, and from there you can also edit.
Why then would you have to make a change to edit and save the content in the **builder.php** page.

**Comment by imdewan** [comment]
See it creates html file with js which redirects to view.php?id=[id]

**Comment by pepiuox** [comment]
> 
> 
> See it creates html file with js which redirects to view.php?id=[id]

When you create a page it redirects you to builder.php, there you can add content or increase a button that returns to the list page, you can also activate the new page button to be a link to add.php

**Comment by imdewan** [comment]
try it. once

**Pull request closed without merging**
